### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by wvdvegt** [playgen/SUGAR-SocialGamification#1]
Hi

Where can I download the swagger definition for SugarEngine?

**Comment by JaredGG** [comment]
We have the full REST API documentation here: http://docs.sugarengine.org/restapi/restapi.html which was generated using swagger but if you require the swagger generated json file you can get it by downloading and running the server: http://docs.sugarengine.org/development/index.html

which when run in development mode in Visual Studio will automatically generate and launch a swagger web page with a url to the actual definition: http://localhost:59400/swagger/v1/swagger.json.
